### ISSUE TITLE
Separate into ansible-r and ansible-rstudio_server

### ISSUE THREAD

**Issue by evilham** [debops/ansible-rstudio_server#2]
For some reason I was mostly done implementing this when I noticed it's here already '^^.

Anyways, the rationale for a separation is that the CRAN repository management and R installation (`ansible-r`) are two things that can, and should, not imply installing R Studio Server (`ansible-rstudio_server`).

One example is wanting to run Shiny (also from R studio).

I could work in the separation as well as in adding `ansible-shiny` if you find that to be worth it.

**Comment by drybjed** [comment]
Sounds good. However, `ansible-r` is... Ugh. How about `ansible-cran`? That would result in `debops.cran` role and `cran__*` variable namespace. I don't see any `^cran*` packages in the Debian Jessie archive, so it looks like there won't be any package name issues, at least for now.

A role for Shiny sounds good. NB, I see that `r-cran-shiny` APT package is available, is that it?

**Comment by evilham** [comment]
> However, `ansible-r` is... Ugh. How about `ansible-cran`?

Brilliant, I was also unsure about `ansible-r` but didn't come up with that, much better one :).

As for the APT package, I'm pretty sure it's not, I think that one is for a Rmarkdown extension, not for the https://shiny.rstudio.com server.

**Comment by evilham** [comment]
Closed pending deprecation of the debops package.

**Comment by drybjed** [comment]
Actually, `debops.cran` role sounds like something useful to have. There's an existing precedent as well: [debops-contrib.neurodebian](https://github.com/debops-contrib/ansible-neurodebian) role. You should reopen this issue and work on the `debops.cran` if you want it.

**Comment by evilham** [comment]
Will do :).

**Comment by drybjed** [comment]
The [`debops.cran`](https://github.com/debops/ansible-cran/) role is now up. Closing this issue.
