### ISSUE TITLE
Pending deprecation

### ISSUE THREAD

**Issue by evilham** [debops/ansible-rstudio_server#4]
This DebOps role is pending deprecation as discussed [here](https://github.com/debops/ansible-rstudio_server/issues/3#issuecomment-312933410) (Issue #3).

When the Policy for deprecating roles is defined, according changes should be made here and this issue should be closed.

**Comment by drybjed** [comment]
It's "DebOps role" actually, from Ansible roles. :-)

**Comment by drybjed** [comment]
Well, somebody commissioned a management gig for a RStudio server  from me, so I'm going to refresh this role pretty soon and make it work on Stretch. Should be ready in a couple of days. I'm closing this issue since the role will be no longer deprecated.
